#!/usr/bin/env bash
# Safety-vs-trusted read parity benchmark (P5 of the memory-safety plan): proves that trusted_input=true
# (which skips only the untrusted-input DoS/OOM budget checks — every bounds check keeps running either
# way, see docs/SAFETY.md) is not measurably faster than the default, fully-checked read. That's the
# "safety costs nothing" claim nanom makes too; this script is the nanolance-side receipt for it.
#
# Usage:
#   bench/read_parity_bench.sh [build_dir] [rows]
#
#   build_dir   path to a configured+built tree (default: ./build). nlbench and nlbench_gendata must
#               already be built there (cmake --build <build_dir> -j).
#   rows        row count for the synthetic dataset (default: 1000000).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD="${1:-$ROOT/build}"
ROWS="${2:-1000000}"
ITERS="${ITERS:-9}"
OUT="$ROOT/bench/read_parity_results.md"

NLBENCH="$BUILD/nlbench"
GENDATA="$BUILD/nlbench_gendata"
if [[ ! -x "$NLBENCH" || ! -x "$GENDATA" ]]; then
    echo "error: nlbench / nlbench_gendata not found in '$BUILD' — configure & build first, e.g.:" >&2
    echo "  cmake -S '$ROOT' -B '$BUILD' -DCMAKE_BUILD_TYPE=Release && cmake --build '$BUILD' -j" >&2
    exit 1
fi

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
DATASET="$TMP/parity.lance"

echo "Generating a $ROWS-row synthetic dataset (mixed fixed-width / low- and high-cardinality utf8 / constant columns) ..." >&2
"$GENDATA" "$DATASET" "$ROWS" >&2

echo "Reading $ITERS times with default (fully-checked) limits ..." >&2
DEFAULT_JSON="$("$NLBENCH" "$DATASET" "$ITERS")"
echo "Reading $ITERS times with trusted_input=true ..." >&2
TRUSTED_JSON="$("$NLBENCH" "$DATASET" "$ITERS" --trusted)"

extract() { python3 -c "import json,sys; print(json.loads(sys.argv[1])[sys.argv[2]])" "$1" "$2"; }
DEFAULT_BEST="$(extract "$DEFAULT_JSON" best_ms)"
DEFAULT_AVG="$(extract "$DEFAULT_JSON" avg_ms)"
TRUSTED_BEST="$(extract "$TRUSTED_JSON" best_ms)"
TRUSTED_AVG="$(extract "$TRUSTED_JSON" avg_ms)"
RATIO="$(python3 -c "print(f'{$TRUSTED_BEST / $DEFAULT_BEST:.3f}')")"

{
    echo "# Read parity: default (safety-first) vs trusted_input"
    echo
    echo "_$(date -u '+%Y-%m-%d %H:%M:%S UTC') · commit \`$(git -C "$ROOT" rev-parse --short HEAD)\`_"
    echo
    echo "Generated by \`bench/read_parity_bench.sh\`. Proves the P5 claim from the memory-safety plan:"
    echo "\`trusted_input=true\` (skips only the untrusted-input DoS/OOM budget checks — bounds checks are"
    echo "unconditional and always run, see [docs/SAFETY.md](../docs/SAFETY.md)) is not measurably faster"
    echo "than the default, fully-checked read. Dataset: $ROWS rows, 4 columns (plain int64, low-cardinality"
    echo "utf8, high-cardinality utf8, constant int64) — a mix the writer auto-encodes as"
    echo "bitpack/RLE/dict-RLE/constant/plain."
    echo
    echo '## Environment'
    echo '```'
    uname -a
    (${CXX:-c++} --version 2>/dev/null | head -1) || true
    echo '```'
    echo
    echo '## Results'
    echo '```'
    printf "%-14s | %10s | %10s\n" "mode" "best ms" "avg ms"
    printf "%-14s-+-%10s-+-%10s\n" "--------------" "----------" "----------"
    printf "%-14s | %10s | %10s\n" "default" "$DEFAULT_BEST" "$DEFAULT_AVG"
    printf "%-14s | %10s | %10s\n" "trusted_input" "$TRUSTED_BEST" "$TRUSTED_AVG"
    echo '```'
    echo
    echo "trusted/default best-ms ratio: **${RATIO}x** (best of $ITERS reads each; ~1.0x means no"
    echo "measurable difference — the checks trusted_input skips already validate once per page/header,"
    echo "not per value, so they cost nothing to begin with)."
} > "$OUT"

echo "Wrote $OUT" >&2
cat "$OUT"
