#!/usr/bin/env bash
# Run the nanolance benchmark locally and write the results to bench/linux-local-results.md.
#
# This is the local-developer counterpart to the CI workflow (.github/workflows/linux-bench.yml),
# which owns bench/linux-ci-results.md. Keeping the two files separate means a local bench run and
# the CI auto-commit can never clash on the same path — no more perpetual diffs / merge pain.
#
# Usage:
#   bench/run-local-bench.sh [build_dir]
#
#   build_dir   path to a configured+built tree (default: ./build). nlbench and arrowipc2lance
#               must already be built there (cmake --build <build_dir> -j).
#
# Commit bench/linux-local-results.md yourself if you want to keep the numbers in the repo.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD="${1:-$ROOT/build}"
OUT="$ROOT/bench/linux-local-results.md"
export NL_BUILD="$BUILD"
export BENCH_TMP="${BENCH_TMP:-/tmp/nlb-local}"

if [[ ! -x "$BUILD/nlbench" && ! -x "$BUILD/nlbench.exe" ]]; then
    echo "error: nlbench not found in '$BUILD' — configure & build first, e.g.:" >&2
    echo "  cmake -S '$ROOT' -B '$BUILD' -DCMAKE_BUILD_TYPE=Release && cmake --build '$BUILD' -j" >&2
    exit 1
fi

mkdir -p "$BENCH_TMP"

echo "Running local benchmark (build=$BUILD, tmp=$BENCH_TMP) ..." >&2
BENCH_TXT="$(python3 "$ROOT/tools/bench.py")"

{
    echo "# Linux local results (developer machine)"
    echo
    echo "_$(date -u '+%Y-%m-%d %H:%M:%S UTC') · commit \`$(git -C "$ROOT" rev-parse --short HEAD)\`_"
    echo
    echo "Generated by \`bench/run-local-bench.sh\`. This file is the local counterpart to the"
    echo "CI-owned \`bench/linux-ci-results.md\` — the two never share a path, so local runs and the"
    echo "CI auto-commit do not collide."
    echo
    echo '## Environment'
    echo '```'
    uname -a
    (${CXX:-c++} --version 2>/dev/null | head -1) || true
    (cmake --version | head -1) || true
    echo '```'
    echo
    echo '## Benchmark (parquet vs rust lance vs nanolance)'
    echo '```'
    echo "$BENCH_TXT"
    echo '```'
} > "$OUT"

echo "Wrote $OUT" >&2
