#!/usr/bin/env python3
"""Render bench/results/matrix.json (tools/bench_matrix.py) as docs/BENCHMARKS.md.

    python tools/bench_report.py [matrix.json] [BENCHMARKS.md]

Numbers are medians in milliseconds. "x" columns are speed ratios: Rust Lance's time divided by
nanolance's, so above 1 means nanolance is faster. Summary lines use the geometric mean of those
ratios, the usual way to average speedups.
"""

from __future__ import annotations

import json
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATEGORIES = [
    ("numeric", "Integers, floats, booleans"),
    ("temporal", "Dates, times, decimals"),
    ("string", "Strings and binary"),
    ("nullable", "Nulls"),
    ("nested", "Vectors, structs, lists, maps"),
    ("mixed", "A realistic table"),
]


def ms(v):
    if v is None:
        return "—"
    return f"{v:,.1f}" if v < 100 else f"{v:,.0f}"


def mb(v):
    return "—" if v is None else f"{v / 1e6:,.2f}"


def ratio(num, den):
    if not num or not den:
        return None
    return num / den


def fx(r):
    return "—" if r is None else f"{r:.2f}x"


def geomean(values):
    values = [v for v in values if v]
    return math.exp(sum(math.log(v) for v in values) / len(values)) if values else None


def render(data) -> str:
    env = data["environment"]
    D = data["datasets"]
    out = []
    w = out.append
    w("# Benchmarks")
    w("")
    w("_Generated by `tools/bench_report.py` from `bench/results/matrix.json`, produced by "
      "`tools/bench_matrix.py`. Rerun both to reproduce on your own machine._")
    w("")
    w(f"**Machine:** {env['cpu']}, {env['cores']} cores, {env['memory_gb']} GB, {env['os']}. "
      f"**Versions:** pylance {env['pylance']} (Rust Lance, file format 2.2), pyarrow {env['pyarrow']}, "
      f"Python {env['python']}, nanolance `{env['nanolance_commit']}` ({env['build']} build). "
      f"**Date:** {env['date']}. Every number is the median of {data['runs']} runs after one warm-up, "
      "files in the page cache.")
    w("")
    w("**Threads.** nanolance reads and writes on one thread, and its C++ runs are pinned to one core. "
      "Rust Lance runs twice: on all cores (its default) and pinned to one core with one CPU and one "
      "I/O thread, so both the out-of-the-box and the per-core comparison are here. pyarrow's Parquet "
      "uses all cores.")
    w("")
    w("**Correctness.** Every read was checked against the source table before it was timed; a reader "
      "that returns different data is listed as a failure, not a time.")
    w("")

    # Summary.
    def collect(fn):
        return [fn(r) for r in D.values()]

    read_1c = geomean(collect(lambda r: ratio(r["read_ms"].get("rust-lance-1c <- rust-lance"),
                                              r["read_ms"].get("nanolance-cpp <- nanolance"))))
    read_4c = geomean(collect(lambda r: ratio(r["read_ms"].get("rust-lance <- rust-lance"),
                                              r["read_ms"].get("nanolance-cpp <- nanolance"))))
    read_retain_4c = geomean(collect(lambda r: ratio(r["read_ms"].get("rust-lance <- rust-lance"),
                                                     r["read_ms"].get("nanolance-cpp-retain <- nanolance"))))
    write_1c = geomean(collect(lambda r: ratio(r["write_ms"].get("rust-lance-1c"), r["write_ms"].get("nanolance-cpp"))))
    write_4c = geomean(collect(lambda r: ratio(r["write_ms"].get("rust-lance"), r["write_ms"].get("nanolance-cpp"))))
    size = geomean(collect(lambda r: ratio(r["size"].get("nanolance"), r["size"].get("rust-lance"))))
    failures = sum(len(r["errors"]) for r in D.values())
    w("## Summary")
    w("")
    w("Geometric mean over all datasets, nanolance C++ against Rust Lance (above 1x: nanolance is faster):")
    w("")
    w("| | vs Rust Lance on 1 core | vs Rust Lance on all cores |")
    w("|---|---:|---:|")
    w(f"| Read (each reads its own file) | {fx(read_1c)} | {fx(read_4c)} |")
    w(f"| Read, nanolance with a memory-retaining allocator | | {fx(read_retain_4c)} |")
    w(f"| Write | {fx(write_1c)} | {fx(write_4c)} |")
    w("")
    w(f"File size, nanolance / Rust Lance: **{size:.3f}** (geometric mean). "
      f"Reads that returned wrong data or failed: **{failures}**.")
    w("")

    has_native = any("rust-native" in r["write_ms"] for r in D.values())
    if has_native:
        py_read = geomean(collect(lambda r: ratio(r["read_ms"].get("rust-lance <- rust-lance"),
                                                  r["read_ms"].get("rust-native <- rust-lance"))))
        py_read1 = geomean(collect(lambda r: ratio(r["read_ms"].get("rust-lance-1c <- rust-lance"),
                                                   r["read_ms"].get("rust-native-1c <- rust-lance"))))
        py_write = geomean(collect(lambda r: ratio(r["write_ms"].get("rust-lance"), r["write_ms"].get("rust-native"))))
        py_write1 = geomean(collect(lambda r: ratio(r["write_ms"].get("rust-lance-1c"),
                                                    r["write_ms"].get("rust-native-1c"))))
        nat_read = geomean(collect(lambda r: ratio(r["read_ms"].get("rust-native <- rust-lance"),
                                                   r["read_ms"].get("nanolance-cpp <- nanolance"))))
        nat_read1 = geomean(collect(lambda r: ratio(r["read_ms"].get("rust-native-1c <- rust-lance"),
                                                    r["read_ms"].get("nanolance-cpp <- nanolance"))))
        nat_write = geomean(collect(lambda r: ratio(r["write_ms"].get("rust-native"), r["write_ms"].get("nanolance-cpp"))))
        nat_write1 = geomean(collect(lambda r: ratio(r["write_ms"].get("rust-native-1c"),
                                                     r["write_ms"].get("nanolance-cpp"))))
        w("### Without Python: the lance crate itself")
        w("")
        w("The same comparison against `tools/lance_rs_bench`, a Rust program using the `lance` crate (12.0.0, "
          "the version pylance 12.0.0 is built from) with no Python in the process:")
        w("")
        w("| | vs Rust native on 1 core | vs Rust native on all cores |")
        w("|---|---:|---:|")
        w(f"| Read | {fx(nat_read1)} | {fx(nat_read)} |")
        w(f"| Write | {fx(nat_write1)} | {fx(nat_write)} |")
        w("")
        w(f"Does Python slow Rust Lance down? pylance's time over the crate's own: reads {fx(py_read1)} (1 core) "
          f"and {fx(py_read)} (all cores), writes {fx(py_write1)} and {fx(py_write)} -- 1.00x would mean no cost.")
        w("")

    mem_keys = [("nanolance-cpp write", "nanolance write"), ("nanolance-cpp-budget write", "nanolance write, 4 MiB budget"),
                ("rust-native write", "Rust write"), ("nanolance-cpp read <- nanolance", "nanolance read"),
                ("rust-native read <- rust-lance", "Rust read")]
    if any(r.get("peak_mb") for r in D.values()):
        wm = geomean(collect(lambda r: ratio(r.get("peak_mb", {}).get("rust-native write"),
                                             r.get("peak_mb", {}).get("nanolance-cpp write"))))
        wb = geomean(collect(lambda r: ratio(r.get("peak_mb", {}).get("rust-native write"),
                                             r.get("peak_mb", {}).get("nanolance-cpp-budget write"))))
        rm = geomean(collect(lambda r: ratio(r.get("peak_mb", {}).get("rust-native read <- rust-lance"),
                                             r.get("peak_mb", {}).get("nanolance-cpp read <- nanolance"))))
        w("## Memory")
        w("")
        w("Peak memory each native process added for one write or read (MB): for a write, over the input "
          "batches it already held; for a read, including the table it returns. nanolance with a 4 MiB "
          "budget commits a fragment whenever it holds 4 MiB, the setting for a device that must bound "
          "its resident memory while saving. Rust is the `lance` crate on all cores.")
        w("")
        w(f"Geometric mean, Rust's peak over nanolance's: writes {fx(wm)} ({fx(wb)} against the 4 MiB budget), "
          f"reads {fx(rm)}.")
        w("")
        w("| dataset | in-memory MB | " + " | ".join(t for _, t in mem_keys) + " |")
        w("|---|---:|" + "---:|" * len(mem_keys))
        for n, r in D.items():
            pk = r.get("peak_mb", {})
            w(f"| `{n}` | {r['arrow_bytes'] / 1e6:,.1f} | " + " | ".join(ms(pk.get(k)) for k, _ in mem_keys) + " |")
        w("")

    fp = data.get("footprint")
    if fp:
        def mbytes(v):
            return "—" if v is None else f"{v / 1e6:,.1f} MB"
        nl, rs = fp["nanolance"], fp["rust"]
        w("## Footprint")
        w("")
        w("| | nanolance | Rust Lance |")
        w("|---|---:|---:|")
        w(f"| Reader + writer program, stripped | {mbytes(nl['bench_binary_bytes'])} | {mbytes(rs['bench_binary_bytes'])} |")
        w(f"| Python package's native library | {mbytes(nl['python_native_lib_bytes'])} | "
          f"{mbytes(rs['python_native_lib_bytes'])} |")
        w(f"| Third-party code linked in | {len(nl['third_party'])} libraries ({', '.join(nl['third_party'])}) | "
          f"{rs['crates'] if rs['crates'] is not None else '—'} crates |")
        w("")
        w(f"The programs: {nl['binary']}; {rs['binary']}. pylance's library also carries the cloud object "
          "stores, which the Rust program leaves out.")
        w("")

    notes = data.get("_notes") or {}
    if notes.get("findings"):
        w("## What the numbers say")
        w("")
        for title, body in notes["findings"]:
            w(f"- **{title}.** {body}")
        w("")
    if notes.get("method"):
        w("## Method")
        w("")
        for line in notes["method"]:
            w(f"- {line}")
        w("")

    for cat, title in CATEGORIES:
        names = [n for n, r in D.items() if r.get("category") == cat]
        if not names:
            continue
        w(f"## {title}")
        w("")
        w("**Read**, ms (each reader on the file its own writer made, then the cross reads):")
        w("")
        w("| dataset | rows | nanolance C++ | + retaining malloc | nanolance Python | Rust Lance 1 core | "
          "Rust Lance all cores | Rust native 1 core | Rust native all cores | Parquet | Rust reads nanolance's | "
          "nanolance reads Rust's |")
        w("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
        for n in names:
            r = D[n]
            R = r["read_ms"]
            w(f"| `{n}` — {r['description']} | {r['rows']:,} | {ms(R.get('nanolance-cpp <- nanolance'))} | "
              f"{ms(R.get('nanolance-cpp-retain <- nanolance'))} | {ms(R.get('nanolance-py <- nanolance'))} | "
              f"{ms(R.get('rust-lance-1c <- rust-lance'))} | {ms(R.get('rust-lance <- rust-lance'))} | "
              f"{ms(R.get('rust-native-1c <- rust-lance'))} | {ms(R.get('rust-native <- rust-lance'))} | "
              f"{ms(R.get('parquet <- parquet'))} | {ms(R.get('rust-lance <- nanolance'))} | "
              f"{ms(R.get('nanolance-cpp <- rust-lance'))} |")
        w("")
        w("**Write** (ms) and **size** (MB):")
        w("")
        w("| dataset | nanolance C++ | + 4 MiB budget | nanolance Python | Rust Lance 1 core | Rust Lance all cores | "
          "Rust native 1 core | Rust native all cores | Parquet | size nanolance | size Rust Lance | size Parquet |")
        w("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
        for n in names:
            r = D[n]
            W, S = r["write_ms"], r["size"]
            w(f"| `{n}` | {ms(W.get('nanolance-cpp'))} | {ms(W.get('nanolance-cpp-budget'))} | {ms(W.get('nanolance-py'))} | "
              f"{ms(W.get('rust-lance-1c'))} | {ms(W.get('rust-lance'))} | {ms(W.get('rust-native-1c'))} | "
              f"{ms(W.get('rust-native'))} | {ms(W.get('parquet'))} | {mb(S.get('nanolance'))} | "
              f"{mb(S.get('rust-lance'))} | {mb(S.get('parquet'))} |")
        w("")
        errs = [(n, k, v) for n in names for k, v in D[n]["errors"].items()]
        if errs:
            w("Failures:")
            w("")
            for n, k, v in errs:
                w(f"- `{n}` {k}: {v}")
            w("")
    return "\n".join(out) + "\n"


def main(argv):
    src = Path(argv[1]) if len(argv) > 1 else ROOT / "bench" / "results" / "matrix.json"
    dst = Path(argv[2]) if len(argv) > 2 else ROOT / "docs" / "BENCHMARKS.md"
    data = json.loads(src.read_text())
    notes = src.with_name("notes.json")  # the findings and method, shared with bench_html.py
    if notes.exists():
        data["_notes"] = json.loads(notes.read_text())
    dst.write_text(render(data))
    print(f"wrote {dst}")


if __name__ == "__main__":
    main(sys.argv)
