#!/usr/bin/env python3
"""Render bench/results/matrix.json (tools/bench_matrix.py) as docs/BENCHMARKS.md.

    python tools/bench_report.py [matrix.json] [BENCHMARKS.md]

Numbers are medians in milliseconds. "x" columns are speed ratios: Rust Lance's time divided by
nanolance's, so above 1 means nanolance is faster. Summary lines use the geometric mean of those
ratios, the usual way to average speedups.
"""

from __future__ import annotations

import json
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATEGORIES = [
    ("numeric", "Numbers"),
    ("temporal", "Dates, times, decimals"),
    ("string", "Strings and binary"),
    ("nullable", "Nulls"),
    ("nested", "Vectors, structs, lists, maps"),
    ("mixed", "A realistic table"),
]


def ms(v):
    if v is None:
        return "—"
    return f"{v:,.1f}" if v < 100 else f"{v:,.0f}"


def mb(v):
    return "—" if v is None else f"{v / 1e6:,.2f}"


def ratio(num, den):
    if not num or not den:
        return None
    return num / den


def fx(r):
    return "—" if r is None else f"{r:.2f}x"


def geomean(values):
    values = [v for v in values if v]
    return math.exp(sum(math.log(v) for v in values) / len(values)) if values else None


def render(data) -> str:
    env = data["environment"]
    D = data["datasets"]
    out = []
    w = out.append
    w("# Benchmarks")
    w("")
    w("_Generated by `tools/bench_report.py` from `bench/results/matrix.json`, produced by "
      "`tools/bench_matrix.py`. Rerun both to reproduce on your own machine._")
    w("")
    w(f"**Machine:** {env['cpu']}, {env['cores']} cores, {env['memory_gb']} GB, {env['os']}. "
      f"**Versions:** pylance {env['pylance']} (Rust Lance, file format 2.2), pyarrow {env['pyarrow']}, "
      f"Python {env['python']}, nanolance `{env['nanolance_commit']}` ({env['build']} build). "
      f"**Date:** {env['date']}. Every number is the median of {data['runs']} runs after one warm-up, "
      "files in the page cache.")
    w("")
    w("**Threads.** nanolance reads and writes on one thread, and its C++ runs are pinned to one core. "
      "Rust Lance runs twice: on all cores (its default) and pinned to one core with one CPU and one "
      "I/O thread, so both the out-of-the-box and the per-core comparison are here. pyarrow's Parquet "
      "uses all cores.")
    w("")
    w("**Correctness.** Every read was checked against the source table before it was timed; a reader "
      "that returns different data is listed as a failure, not a time.")
    w("")

    # Summary.
    def collect(fn):
        return [fn(r) for r in D.values()]

    read_1c = geomean(collect(lambda r: ratio(r["read_ms"].get("rust-lance-1c <- rust-lance"),
                                              r["read_ms"].get("nanolance-cpp <- nanolance"))))
    read_4c = geomean(collect(lambda r: ratio(r["read_ms"].get("rust-lance <- rust-lance"),
                                              r["read_ms"].get("nanolance-cpp <- nanolance"))))
    read_retain_4c = geomean(collect(lambda r: ratio(r["read_ms"].get("rust-lance <- rust-lance"),
                                                     r["read_ms"].get("nanolance-cpp-retain <- nanolance"))))
    write_1c = geomean(collect(lambda r: ratio(r["write_ms"].get("rust-lance-1c"), r["write_ms"].get("nanolance-cpp"))))
    write_4c = geomean(collect(lambda r: ratio(r["write_ms"].get("rust-lance"), r["write_ms"].get("nanolance-cpp"))))
    size = geomean(collect(lambda r: ratio(r["size"].get("nanolance"), r["size"].get("rust-lance"))))
    failures = sum(len(r["errors"]) for r in D.values())
    w("## Summary")
    w("")
    w("Geometric mean over all datasets, nanolance C++ against Rust Lance (above 1x: nanolance is faster):")
    w("")
    w("| | vs Rust Lance on 1 core | vs Rust Lance on all cores |")
    w("|---|---:|---:|")
    w(f"| Read (each reads its own file) | {fx(read_1c)} | {fx(read_4c)} |")
    w(f"| Read, nanolance with a memory-retaining allocator | | {fx(read_retain_4c)} |")
    w(f"| Write | {fx(write_1c)} | {fx(write_4c)} |")
    w("")
    w(f"File size, nanolance / Rust Lance: **{size:.3f}** (geometric mean). "
      f"Reads that returned wrong data or failed: **{failures}**.")
    w("")

    for cat, title in CATEGORIES:
        names = [n for n, r in D.items() if r.get("category") == cat]
        if not names:
            continue
        w(f"## {title}")
        w("")
        w("**Read**, ms (each reader on the file its own writer made, then the cross reads):")
        w("")
        w("| dataset | rows | nanolance C++ | + retaining malloc | nanolance Python | Rust Lance 1 core | "
          "Rust Lance all cores | Parquet | Rust reads nanolance's | nanolance reads Rust's |")
        w("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
        for n in names:
            r = D[n]
            R = r["read_ms"]
            w(f"| `{n}` — {r['description']} | {r['rows']:,} | {ms(R.get('nanolance-cpp <- nanolance'))} | "
              f"{ms(R.get('nanolance-cpp-retain <- nanolance'))} | {ms(R.get('nanolance-py <- nanolance'))} | "
              f"{ms(R.get('rust-lance-1c <- rust-lance'))} | {ms(R.get('rust-lance <- rust-lance'))} | "
              f"{ms(R.get('parquet <- parquet'))} | {ms(R.get('rust-lance <- nanolance'))} | "
              f"{ms(R.get('nanolance-cpp <- rust-lance'))} |")
        w("")
        w("**Write** (ms) and **size** (MB):")
        w("")
        w("| dataset | nanolance C++ | nanolance Python | Rust Lance 1 core | Rust Lance all cores | Parquet | "
          "size nanolance | size Rust Lance | size Parquet |")
        w("|---|---:|---:|---:|---:|---:|---:|---:|---:|")
        for n in names:
            r = D[n]
            W, S = r["write_ms"], r["size"]
            w(f"| `{n}` | {ms(W.get('nanolance-cpp'))} | {ms(W.get('nanolance-py'))} | {ms(W.get('rust-lance-1c'))} | "
              f"{ms(W.get('rust-lance'))} | {ms(W.get('parquet'))} | {mb(S.get('nanolance'))} | "
              f"{mb(S.get('rust-lance'))} | {mb(S.get('parquet'))} |")
        w("")
        errs = [(n, k, v) for n in names for k, v in D[n]["errors"].items()]
        if errs:
            w("Failures:")
            w("")
            for n, k, v in errs:
                w(f"- `{n}` {k}: {v}")
            w("")
    return "\n".join(out) + "\n"


def main(argv):
    src = Path(argv[1]) if len(argv) > 1 else ROOT / "bench" / "results" / "matrix.json"
    dst = Path(argv[2]) if len(argv) > 2 else ROOT / "docs" / "BENCHMARKS.md"
    dst.write_text(render(json.loads(src.read_text())))
    print(f"wrote {dst}")


if __name__ == "__main__":
    main(sys.argv)
